Controllers/NguoiDungController.cs
using Source.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Source.Controllers
{
    public class NguoiDungController : Controller
    {
        private QuanLyTaiSanCNTTEntities db = new QuanLyTaiSanCNTTEntities();

        // GET: /NguoiDung/
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            if (Session["QL_ND"] != null)
            {
                //Đơn vị
                var dsTenDonVi = db.DON_VI.Select(a => a.TEN_DON_VI)
                                          .ToList()
                                          .Distinct();
                ViewBag.donVi = new SelectList(dsTenDonVi);

                //Nhóm người dùng
                var dsTenNhom = db.NHOM_NGUOI_DUNG.Select(a => a.TEN_NHOM)
                                                  .ToList()
                                                  .Distinct();                
                ViewBag.tenNhom = new SelectList(dsTenNhom);

                var pHAN_QUYEN = db.NHOM_ND_CHUCNANG.Where(a => a.MA_NHOM == Session["NHOM_ND"].ToString()
                                                             && a.MA_CHUC_NANG == 15);                

                ViewBag.Them = pHAN_QUYEN.Where(a => a.MA_QUYEN == 1);
                ViewBag.Sua = pHAN_QUYEN.Where(a => a.MA_QUYEN == 3);
            }
            else
            {
                return HttpNotFound("You have no accesss permissions at this");
            }

            var nguoi_dung = db.NGUOI_DUNG.Include(n => n.DON_VI);
            return View(await nguoi_dung.ToListAsync());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index(FormCollection form, string SAVE, string EDIT, string donVi, string tenNhom, string value)
        {
            var pHAN_QUYEN = db.NHOM_ND_CHUCNANG.Where(a => a.MA_NHOM == Session["NHOM_ND"].ToString()
                                                             && a.MA_CHUC_NANG == 15);

            ViewBag.Them = pHAN_QUYEN.Where(a => a.MA_QUYEN == 1);
            ViewBag.Sua = pHAN_QUYEN.Where(a => a.MA_QUYEN == 3);

            //Đơn vị
            var dsTenDonVi = db.DON_VI.Select(a => a.TEN_DON_VI)
                                      .ToList()
                                      .Distinct();
            ViewBag.donVi = new SelectList(dsTenDonVi);

            //Nhóm người dùng
            var dsTenNhom = db.NHOM_NGUOI_DUNG.Select(a => a.TEN_NHOM)
                                              .ToList()
                                              .Distinct();
            ViewBag.tenNhom = new SelectList(dsTenNhom);


            var nguoi_dung = db.NGUOI_DUNG.Include(n => n.DON_VI);

            if (!String.IsNullOrEmpty(SAVE))
            {
                var temp = form["MA_ND"].ToString();
                if (String.IsNullOrEmpty(form["MA_NHOM"]) || String.IsNullOrEmpty(form["MA_DON_VI"])
                   || String.IsNullOrEmpty(form["MA_ND"]) || String.IsNullOrEmpty(form["TEN_ND"]))
                {
                    ViewBag.ErrorMessage = "Xin nhập đầy đủ thông tin";
                }
                else if (db.NGUOI_DUNG.FirstOrDefault(a => a.MA_ND == temp) != null)
                {
                    ViewBag.ErrorMessage = "Trùng mã người dùng";
                }
                else
                {
                    //Thêm người dùng
                    NGUOI_DUNG create_ND = THEM_NGUOI_DUNG(form);

                    //Thêm nhóm người dùng
                    NHOM_ND create_NHOM_ND = THEM_NHOM_NGUOI_DUNG(form);

                    if (ModelState.IsValid)
                    {
                        db.NGUOI_DUNG.Add(create_ND);
                        db.NHOM_ND.Add(create_NHOM_ND);
                        await db.SaveChangesAsync();

                        ViewBag.ErrorMessage = "Thêm thành công";
                    }
                }
            }
            else if (!String.IsNullOrEmpty(EDIT))
            {         
                //Sửa người dùng
                if(SUA_NGUOI_DUNG(form) != null)
                {
                    db.Entry(SUA_NGUOI_DUNG(form)).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                }

                //Sửa nhóm người dùng
                if (SUA_NHOM_NGUOI_DUNG(form) != null)
                {
                    db.Entry(SUA_NHOM_NGUOI_DUNG(form)).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                }
                ViewBag.ErrorMessage = "Sửa thành công";
            }
            else
            {
                if (!String.IsNullOrEmpty(donVi))
                {
                    nguoi_dung = nguoi_dung.Where(data => data.DON_VI.TEN_DON_VI == donVi);
                }
                else if (!String.IsNullOrEmpty(tenNhom))
                {
                    //var mA_ND = db.NHOM_ND.Where(a => a.NHOM_NGUOI_DUNG.TEN_NHOM == tenNhom)
                    //                      .Select(a => a.MA_ND)
                    //                      .ToList();

                    //nguoi_dung = nguoi_dung.Where(a => a.MA_ND == "");

                    var nhom_ND = new List<NGUOI_DUNG>();
                    foreach (var a in db.NHOM_ND)
                    {
                        if (a.NHOM_NGUOI_DUNG.TEN_NHOM == tenNhom)
                        {
                            nhom_ND.Add(a.NGUOI_DUNG);
                        }
                    }
                    return View(nhom_ND.ToList());
                }
            }
            return View(await nguoi_dung.ToListAsync());
        }

        #region Thêm người dùng
        public NGUOI_DUNG THEM_NGUOI_DUNG(FormCollection form)
        {
            NGUOI_DUNG nGUOI_DUNG = new NGUOI_DUNG();
            nGUOI_DUNG.MA_ND = form["MA_ND"];
            nGUOI_DUNG.TEN_ND = form["TEN_ND"];
            nGUOI_DUNG.DIEN_THOAI = Int32.Parse(form["DIEN_THOAI"]);
            nGUOI_DUNG.EMAIL = form["EMAIL"];
            nGUOI_DUNG.MA_DON_VI = Int32.Parse(form["MA_DON_VI"]);
            return nGUOI_DUNG;
        }
        #endregion

        #region Thêm nhóm người dùng
        public NHOM_ND THEM_NHOM_NGUOI_DUNG(FormCollection form)
        {
            NHOM_ND nHOM_ND = new NHOM_ND();
            nHOM_ND.MA_ND = form["MA_ND"];            
            nHOM_ND.MA_NHOM = form["MA_NHOM"];
            return nHOM_ND;
        }
        #endregion

        #region Sửa người dùng
        public NGUOI_DUNG SUA_NGUOI_DUNG(FormCollection form)
        {            
            //Sửa người dùng
            NGUOI_DUNG eDIT_NGUOI_DUNG = new NGUOI_DUNG();
            eDIT_NGUOI_DUNG.MA_ND = form["MA_ND"];
            eDIT_NGUOI_DUNG.TEN_ND = form["TEN_ND"];
            eDIT_NGUOI_DUNG.MA_DON_VI = Int32.Parse(form["MA_DON_VI"]);
            eDIT_NGUOI_DUNG.DIEN_THOAI = Int32.Parse(form["DIEN_THOAI"]);
            eDIT_NGUOI_DUNG.EMAIL = form["EMAIL"];

            //NGUOI_DUNG nGUOI_DUNG = db.NGUOI_DUNG.FirstOrDefault(x => x.MA_ND == eDIT_NGUOI_DUNG.MA_ND);
            //if (nGUOI_DUNG.Equals(eDIT_NGUOI_DUNG))
            //{
            //    return null;
            //}
            return eDIT_NGUOI_DUNG;
        }
        #endregion

        #region Sửa nhóm người dùng
        public NHOM_ND SUA_NHOM_NGUOI_DUNG(FormCollection form)
        {
            //Sửa nhóm người dùng
            NHOM_ND eDIT_NHOM_ND = new NHOM_ND();
            eDIT_NHOM_ND.MA_NHOM_ND = Int32.Parse(form["MA_NHOM_ND"]);
            eDIT_NHOM_ND.MA_ND = form["MA_ND"];
            eDIT_NHOM_ND.MA_NHOM = form["MA_NHOM"];

            NHOM_ND nHOM_ND = db.NHOM_ND.FirstOrDefault(x => x.MA_NHOM_ND == eDIT_NHOM_ND.MA_NHOM_ND);
            if (nHOM_ND.MA_NHOM == eDIT_NHOM_ND.MA_NHOM)
            {
                return null;
            }
            return eDIT_NHOM_ND;
        }
        #endregion        

        // GET: /NguoiDung/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NGUOI_DUNG nguoi_dung = await db.NGUOI_DUNG.FindAsync(id);
            if (nguoi_dung == null)
            {
                return HttpNotFound();
            }
            return View(nguoi_dung);
        }

        //public bool DeepEquals(NGUOI_DUNG obj, NGUOI_DUNG another)
        //{
        //    //if (ReferenceEquals(obj, another))
        //    //{
        //    //    return true;
        //    //}
        //    if ((obj == null) || (another == null)) return false;
        //    //So sánh class của 2 object, nếu khác nhau thì trả fail
        //    //if (obj.GetType() != another.GetType())
        //    //{
        //    //    return false;
        //    //}

        //    //Lấy toàn bộ các properties của obj
        //    //sau đó so sánh giá trị của từng property
        //    //foreach (var property in obj.GetType().GetProperties())
        //    //{
        //    //    var objValue = property.GetValue(obj);
        //    //    var anotherValue = property.GetValue(another);
        //    //    if (!objValue.Equals(anotherValue))
        //    //    {
        //    //        return false;
        //    //    }
        //    //}
        //    foreach(var item in obj.GetType())
        //    {
        //        if()
        //        {

        //        }
        //    }

        //    return true;
        //}

        // GET: /NguoiDung/Create
        public ActionResult Create()
        {

Views/NguoiDung/Index.cshtml
@model IEnumerable<Source.Models.NGUOI_DUNG>

@{
    ViewBag.Title = "Index";
}

<main>
    <div class="container link">
        <p>Trang chủ > Quản lý người dùng > Người dùng</p>
        <hr />
    </div>
    <section class="container" id="nguoi-dung">
        <h1 class="title">NGƯỜI DÙNG</h1>
        <div class="div-nd">
            <div class="them-nd">
                <h4 class="sub-title">
                    <span id="them-sua">Thêm</span> người dùng
                </h4>
                <div id="ErrorMessage">
                    @if (ViewBag.ErrorMessage != null)
                    {
                        <p id="tb-sm">@ViewBag.ErrorMessage</p>
                    }
                </div>
                @using (Html.BeginForm("Index", "NguoiDung", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <form action="">
                        <div class="form-group">
                            <label for="">Mã ND:</label>
                            <input class="form-control"
                                   id="MA_ND"
                                   name="MA_ND"
                                   placeholder=""/>
                        </div>
                        <div class="form-group">
                            <label for="">Tên ND:</label>
                            <input class="form-control"
                                   id="TEN_ND"
                                   name="TEN_ND"
                                   aria-describedby="emailHelp"
                                   placeholder="" />
                        </div>
                        <div class="form-group">
                            <label for="">Nhóm người dùng:</label>
                            <select class="form-control" name="MA_NHOM" id="MA_NHOM"></select>
                        </div>
                        <div class="form-group">
                            <label for="">Đơn vị:</label>
                            <select class="form-control" name="MA_DON_VI" id="MA_DON_VI"></select>
                        </div>
                        <div class="form-group">
                            <label for="">SĐT:</label>
                            <input type="number"
                                   class="form-control"
                                   id="DIEN_THOAI"
                                   name="DIEN_THOAI"
                                   aria-describedby="emailHelp"
                                   placeholder="" />
                        </div>
                        <div class="form-group">
                            <label for="">Email:</label>
                            <input type="email"
                                   class="form-control"
                                   id="EMAIL"
                                   name="EMAIL"
                                   aria-describedby="emailHelp"
                                   placeholder="">
                        </div>
                        <div class="form-group">
                            <input type="text"
                                   class="form-control"
                                   id="MA_NHOM_ND"
                                   name="MA_NHOM_ND"
                                   aria-describedby="emailHelp"
                                   placeholder=""
                                   hidden>
                        </div>

                        @if (ViewBag.Them != null)
                        {
                            <button type="submit" id="SAVE" name="SAVE" value="save" class="them">THÊM</button>
                        }
                        @if (ViewBag.Sua != null)
                        {
                            <button type="submit" id="EDIT" name="EDIT" value="edit" class="sua d-none">SỬA</button>
                            <button class="reset d-none">HỦY</button>
                        }

                    </form>
                }
            </div>
            <div class="ds-nd">
                <h4 class="sub-title">
                    Danh sách người dùng
                </h4>
                @*"Index", "NguoiDung", FormMethod.Get*@
                @using (Html.BeginForm("Index", "NguoiDung", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <div class="loc">
                        <h4><i class="fas fa-filter"></i></h4>
                        <div class="div-filter">
                            <div class="filter">
                                <label for="">Đơn vị</label>
                                @Html.DropDownList("donVi", null, "Tất cả", new
                                {
                                    @class = "form-control",
                                    @placeholder = "",
                                    @onchange = @"form.submit();"
                                })
                            </div>
                            <div class="filter">
                                <label for="">Nhóm</label>
                                @Html.DropDownList("tenNhom", null, "Tất cả", new
                                {
                                    @class = "form-control",
                                    @placeholder = "",
                                    @onchange = @"form.submit();"
                                })
                            </div>
                        </div>
                    </div>
                }

                <div class="nguoi-dung">
                    <table>
                        <tr>
                            <th>Mã người dùng</th>
                            <th>Tên người dùng</th>
                            <th>Đơn vị</th>
                            <th>Nhóm</th>
                            <th>Điện thoại</th>
                            <th>Email</th>

                        </tr>
                        @using (Html.BeginForm("Index", "NguoiDung", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true)
                            foreach (var item in Model)
                            {
                                <tr class="tablinks" onclick="btn_Edit(event, '@item.MA_ND')">
                                    <td>
                                        <span id="@item.MA_ND" class="btn_edit" ><i class="far fa-edit" onclick="Edit('@item.MA_ND')"></i></span>
                                        @Html.DisplayFor(modelItem => item.MA_ND)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.TEN_ND)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DON_VI.TEN_DON_VI)
                                    </td>
                                    <td>
                                        @foreach (var nd in item.NHOM_ND)
                                        {
                                            if (nd.MA_ND == item.MA_ND)
                                            {
                                                @Html.DisplayFor(m => nd.NHOM_NGUOI_DUNG.TEN_NHOM)<br />
                                            }
                                        }
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.DIEN_THOAI)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.EMAIL)
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            </div>
        </div>


    </section>
</main>

<script>
    $(document).ready(function () {
        $.ajax({
            type: "GET",
            url: "/Script/get_DON_VI",
            data: "{}",
            success: function (data) {
                var s = '<option disabled selected value>Xin chọn đơn vị</option>';
                for (var i = 0; i < data.length; i++) {
                    s += '<option value="' + data[i].MA_DON_VI + '">' + data[i].TEN_DON_VI + '</option>';
                }
                $("#MA_DON_VI").html(s);
            }
        });

        $.ajax({
            type: "GET",
            url: "/Script/get_NHOM_ND",
            data: "{}",
            success: function (data) {
                var s = '<option disabled selected value>Xin chọn đơn vị</option>';
                for (var i = 0; i < data.length; i++) {
                    s += '<option value="' + data[i].MA_NHOM + '">' + data[i].TEN_NHOM + '</option>';
                }
                $("#MA_NHOM").html(s);
            }
        });
    });

    function Edit(row) {
        $.ajax({
            type: "GET",
            url: "/Script/get_THONG_TIN_ND",
            data: { mA_ND: row },
            success: function (data) {
                $("#MA_ND").val(row);
                $("#TEN_ND").val(data.TEN_ND);
                $("#MA_NHOM").val(data.MA_NHOM);
                $("#MA_DON_VI").val(data.MA_DON_VI);
                $("#DIEN_THOAI").val(data.DIEN_THOAI);
                $("#EMAIL").val(data.EMAIL);
                $("#MA_NHOM_ND").val(data.MA_NHOM_ND);
            }
        });
        document.getElementById("MA_ND").setAttribute("readonly", "readonly");
    }        
</script>
