Controllers/NhomNguoiDungController.cs
using Source.Models;
using System;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Source.Controllers
{
    public class NhomNguoiDungController : Controller
    {
        private QuanLyTaiSanCNTTEntities db = new QuanLyTaiSanCNTTEntities();

        // GET: /NhomNguoiDung/
        public async Task<ActionResult> Index()
        {
            var nhom_nguoi_dung = db.NHOM_NGUOI_DUNG.Include(n => n.NHOM_ND_CHUCNANG);

            if (Session["QL_ND"] != null)
            {                
                var pHAN_QUYEN = db.NHOM_ND_CHUCNANG.Where(a => a.MA_NHOM == Session["NHOM_ND"].ToString()
                                                             && a.MA_CHUC_NANG == 16);

                ViewBag.Them = pHAN_QUYEN.Where(a => a.MA_QUYEN == 1);
                ViewBag.Sua = pHAN_QUYEN.Where(a => a.MA_QUYEN == 3);
            }
            else
            {
                return HttpNotFound("You have no accesss permissions at this");
            }

            return View(await nhom_nguoi_dung.ToListAsync());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Index([Bind(Include = "MA_NHOM,TEN_NHOM,GHI_CHU")] NHOM_NGUOI_DUNG cREATE_NHOM_NGUOI_DUNG, string SAVE, string EDIT)
        {
            var pHAN_QUYEN = db.NHOM_ND_CHUCNANG.Where(a => a.MA_NHOM == Session["NHOM_ND"].ToString()
                                                             && a.MA_CHUC_NANG == 16);

            ViewBag.Them = pHAN_QUYEN.Where(a => a.MA_QUYEN == 1);
            ViewBag.Sua = pHAN_QUYEN.Where(a => a.MA_QUYEN == 3);

            var nHOM_NGUOI_DUNG = db.NHOM_NGUOI_DUNG.Include(n => n.NHOM_ND_CHUCNANG);

            if (!String.IsNullOrEmpty(SAVE))
            {
                if (String.IsNullOrEmpty(cREATE_NHOM_NGUOI_DUNG.MA_NHOM) || String.IsNullOrEmpty(cREATE_NHOM_NGUOI_DUNG.TEN_NHOM))
                {
                    ViewBag.ErrorMessage = "Xin nhập đầy đủ thông tin";
                }
                else if (nHOM_NGUOI_DUNG.FirstOrDefault(a => a.MA_NHOM == cREATE_NHOM_NGUOI_DUNG.MA_NHOM) != null)
                {
                    ViewBag.ErrorMessage = "Trùng mã nhóm người dùng";
                }
                else if (ModelState.IsValid)
                {
                    db.NHOM_NGUOI_DUNG.Add(cREATE_NHOM_NGUOI_DUNG);
                    await db.SaveChangesAsync();

                    ViewBag.ErrorMessage = "Thêm thành công";
                }
            }
            else if (!String.IsNullOrEmpty(EDIT))
            {
                NHOM_NGUOI_DUNG eDIT_NHOM_NGUOI_DUNG = nHOM_NGUOI_DUNG.Where(a => a.MA_NHOM == cREATE_NHOM_NGUOI_DUNG.MA_NHOM).FirstOrDefault();
                eDIT_NHOM_NGUOI_DUNG.TEN_NHOM = cREATE_NHOM_NGUOI_DUNG.TEN_NHOM;
                eDIT_NHOM_NGUOI_DUNG.GHI_CHU = cREATE_NHOM_NGUOI_DUNG.GHI_CHU;

                if (ModelState.IsValid)
                {
                    db.Entry(eDIT_NHOM_NGUOI_DUNG).State = EntityState.Modified;
                    await db.SaveChangesAsync();

                    ViewBag.ErrorMessage = "Sửa thành công";
                }

            }
            return View(await nHOM_NGUOI_DUNG.ToListAsync());
        }

        // GET: /NhomNguoiDung/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHOM_NGUOI_DUNG nhom_nguoi_dung = await db.NHOM_NGUOI_DUNG.FindAsync(id);
            if (nhom_nguoi_dung == null)
            {
                return HttpNotFound();
            }
            return View(nhom_nguoi_dung);
        }

        // GET: /NhomNguoiDung/Create
        public ActionResult Create()
        {
            ViewBag.MA_NHOM = new SelectList(db.NHOM_ND_CHUCNANG, "MA_NHOM", "MA_NHOM");
            return View();
        }

        // POST: /NhomNguoiDung/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "MA_NHOM,TEN_NHOM,GHI_CHU")] NHOM_NGUOI_DUNG nhom_nguoi_dung)
        {
            //var nhom_nguoi_dung = new NHOM_NGUOI_DUNG();
            //nhom_nguoi_dung.MA_NHOM = form["MA_NHOM"];
            //nhom_nguoi_dung.TEN_NHOM = form["TEN_NHOM"];
            //nhom_nguoi_dung.GHI_CHU = form["GHI_CHU"];
            if (db.NHOM_NGUOI_DUNG.Count(a => a.MA_NHOM == nhom_nguoi_dung.MA_NHOM) > 0)
            {
                return new HttpStatusCodeResult(404, "Trùng mã nhóm người dùng");
            }

            else if (ModelState.IsValid)
            {
                db.NHOM_NGUOI_DUNG.Add(nhom_nguoi_dung);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Index");
        }

        // GET: /NhomNguoiDung/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHOM_NGUOI_DUNG nhom_nguoi_dung = await db.NHOM_NGUOI_DUNG.FindAsync(id);
            if (nhom_nguoi_dung == null)
            {
                return HttpNotFound();
            }
            ViewBag.MA_NHOM = new SelectList(db.NHOM_ND_CHUCNANG, "MA_NHOM", "MA_NHOM", nhom_nguoi_dung.MA_NHOM);
            return View(nhom_nguoi_dung);
        }

        // POST: /NhomNguoiDung/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "MA_NHOM,TEN_NHOM,GHI_CHU")] NHOM_NGUOI_DUNG nhom_nguoi_dung)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nhom_nguoi_dung).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.MA_NHOM = new SelectList(db.NHOM_ND_CHUCNANG, "MA_NHOM", "MA_NHOM", nhom_nguoi_dung.MA_NHOM);
            return View(nhom_nguoi_dung);
        }

        // GET: /NhomNguoiDung/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NHOM_NGUOI_DUNG nhom_nguoi_dung = await db.NHOM_NGUOI_DUNG.FindAsync(id);
            if (nhom_nguoi_dung == null)
            {
                return HttpNotFound();
            }
            return View(nhom_nguoi_dung);
        }

        // POST: /NhomNguoiDung/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            NHOM_NGUOI_DUNG nhom_nguoi_dung = await db.NHOM_NGUOI_DUNG.FindAsync(id);
            db.NHOM_NGUOI_DUNG.Remove(nhom_nguoi_dung);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/NhomNguoiDung/Index.cshtml
@model IEnumerable<Source.Models.NHOM_NGUOI_DUNG>

@{
    ViewBag.Title = "Index";
}

<main>
    <div class="container link">
        <p>Trang chủ > Quản lý người dùng > Nhóm người dùng</p>
        <hr />
    </div>
    <section class="container" id="nhom-nd">
        <h1 class="title">NHÓM NGƯỜI DÙNG</h1>
        <div class="div-nhom-nd">
            <div class="them-nhom-nd">
                <h4 class="sub-title">
                    <span id="them-sua">Thêm</span> nhóm người dùng
                </h4>
                <div id="ErrorMessage">
                    @if (ViewBag.ErrorMessage != null)
                    {
                        <p id="tb-sm">@ViewBag.ErrorMessage</p>
                    }
                </div>
                @using (Html.BeginForm("Index", "NhomNguoiDung", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true)
                    <form>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Mã nhóm người dùng</label>
                            <input class="form-control"
                                   id="MA_NHOM"
                                   name="MA_NHOM"
                                   aria-describedby="emailHelp"
                                   placeholder="" />
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Tên nhóm người dùng</label>
                            <input class="form-control"
                                   id="TEN_NHOM"
                                   name="TEN_NHOM"
                                   aria-describedby="emailHelp"
                                   placeholder="" />
                        </div>

                        <div class="form-group">
                            <label for="exampleInputEmail1">Ghi chú</label>
                            <textarea class="form-control"
                                      id="GHI_CHU"
                                      name="GHI_CHU"
                                      aria-describedby="emailHelp"
                                      placeholder=""></textarea>
                        </div>



                        @if (ViewBag.Them != null)
                        {
                            <button type="submit" id="SAVE" name="SAVE" value="save" class="them">THÊM</button>
                        }
                        @if (ViewBag.Sua != null)
                        {
                            <button type="submit" id="EDIT" name="EDIT" value="edit" class="sua d-none">SỬA</button>
                            <button class="reset d-none">HỦY</button>
                        }
                    </form>
                }
            </div>
            <div class="ds-nnd">
                <h4 class="sub-title">
                    Danh sách Nhóm người dùng
                </h4>
                <table>
                    <tr>
                        <th>Mã nhóm ND</th>
                        <th>Tên nhóm</th>
                        <th>Ghi chú</th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr class="tablinks" onclick="btn_Edit(event, '@item.MA_NHOM')">
                            <td>
                                <span id="@item.MA_NHOM" class="btn_edit" onclick="Edit('@item.MA_NHOM')"><i class="far fa-edit"></i></span>
                                @Html.DisplayFor(modelItem => item.MA_NHOM)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.TEN_NHOM)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.GHI_CHU)
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
    </section>
</main>

<script>
    function Edit(row) {
        $.ajax({
            type: "GET",
            url: "/Script/get_THONG_TIN_NHOM_ND",
            data: { mA_NHOM: row },
            success: function (data) {
                $("#MA_NHOM").val(row);
                $("#TEN_NHOM").val(data.TEN_NHOM);
                $("#GHI_CHU").val(data.GHI_CHU);
            }
        });
        document.getElementById("MA_NHOM").setAttribute("readonly", "readonly");
    }
</script>